-- noinspection SqlNoDataSourceInspectionForFile

DROP TABLE NAMEX.APPLICATION_LOG CASCADE CONSTRAINTS;

CREATE TABLE NAMEX.APPLICATION_LOG
(
  PROGRAM_NAME  VARCHAR2(20 BYTE)               NOT NULL,
  LOG_DATE      DATE                            NOT NULL,
  ERROR_CODE    NUMBER,
  LOG_MESSAGE   VARCHAR2(4000 BYTE)
);
