---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "notebook-report"
  annotations:
    description: "Scheduled Task to generate notebook report"
    tags: "cronjob,notebook"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "notebook-report"
  spec:
    concurrencyPolicy: "Forbid"
    schedule: "30 7 * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "notebook-report"
              image: "docker-registry.default.svc:5000/servicebc-ne-tools/notebook-report:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                  - name: PG_USER
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql-${ENV_TAG}
                  - name: PG_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql-${ENV_TAG}
                  - name: PG_DB_NAME
                    valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: postgresql
                  - name: PG_HOST
                    value: 'postgresql-${ENV_TAG}'
                  - name: PG_PORT
                    value: '5432'      
                  - name: APP_FILE
                    value: 'notebookreport.py'                      
                  - name: SENDER_EMAIL
                    value: 'namex@noreply.github.com'
                  - name: ERROR_EMAIL_RECIPIENTS
                    value: '[sbc_itoperationssupport@gov.bc.ca, steven.chen@gov.bc.ca]'
                  - name: DAILY_REPORT_RECIPIENTS
                    value: '[Debbie.Blyth@gov.bc.ca, Sinead.OCallaghan@gov.bc.ca, steven.chen@gov.bc.ca]'
                  - name: WEEKLY_REPORT_RECIPIENTS
                    value: '[Debbie.Blyth@gov.bc.ca, Sinead.OCallaghan@gov.bc.ca, Karla.Maria.Ramirez@gov.bc.ca, steven.chen@gov.bc.ca]'  
                  - name: EMAIL_SMTP
                    value: 'apps.smtp.gov.bc.ca'  
                  - name: RETRY_TIMES
                    value: '5'  
                  - name: RETRY_INTERVAL
                    value: '600'                      
                  - name: ENVIRONMENT
                    value: '${ENV_TAG}'  
                  - name: WEEK_REPORT_DATE
                    value: '[0]'                  
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "prod"
        },        
]
