---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "solr-synonym-updater"
  annotations:
    description: "Scheduled Task to concatenate multi-word synonyms into single words in the postgres-solr database"
    tags: "cronjob"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "solr-synonym-updater"
  spec:
    schedule: "* 23 * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "solr-synonym-updater"
              image: "docker-registry.default.svc:5000/servicebc-ne-tools/solr-synonym-updater:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                  - name: DATABASE_USERNAME
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql-solr
                  - name: DATABASE_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql-solr
                  - name: DATABASE_NAME
                    valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: postgresql-solr
                  - name: DATABASE_HOST
                    value: 'postgresql-solr'
                  - name: DATABASE_PORT
                    value: '5432'
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "dev"
        },
]