# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.payments_api import PaymentsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.payments_api.PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_payment(self):
        """Test case for create_payment

        Create payment records  # noqa: E501
        """
        pass

    def test_get_payment(self):
        """Test case for get_payment

        Get Payment  # noqa: E501
        """
        pass

    def test_update_payment(self):
        """Test case for update_payment

        Update payment records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
