# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.transactions_api import TransactionsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_transaction(self):
        """Test case for create_transaction

        Create a transaction  # noqa: E501
        """
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        Get Transaction  # noqa: E501
        """
        pass

    def test_get_transactions(self):
        """Test case for get_transactions

        Get Transactions  # noqa: E501
        """
        pass

    def test_update_transaction(self):
        """Test case for update_transaction

        Update a transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
