# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.business_info import BusinessInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestBusinessInfo(unittest.TestCase):
    """BusinessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BusinessInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.business_info.BusinessInfo()  # noqa: E501
        if include_optional :
            return BusinessInfo(
                business_identifier = '0', 
                business_name = '0', 
                contact_info = [
                    openapi_client.models.contact_info.ContactInfo(
                        first_name = '0', 
                        last_name = '0', 
                        address = '0', 
                        city = '0', 
                        province = '0', 
                        postal_code = '0', )
                    ]
            )
        else :
            return BusinessInfo(
        )

    def testBusinessInfo(self):
        """Test BusinessInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
