# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.receipts_api import ReceiptsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestReceiptsApi(unittest.TestCase):
    """ReceiptsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.receipts_api.ReceiptsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_receipt(self):
        """Test case for get_receipt

        Get receipt for the payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
