# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.payment import Payment  # noqa: E501
from openapi_client.rest import ApiException

class TestPayment(unittest.TestCase):
    """Payment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Payment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.payment.Payment()  # noqa: E501
        if include_optional :
            return Payment(
                links = [
                    openapi_client.models.links.Links(
                        self = '0', 
                        collection = '0', )
                    ], 
                id = 56, 
                created_by = '0', 
                created_on = '0', 
                invoices = [
                    openapi_client.models.invoice.Invoice(
                        _links = [
                            openapi_client.models.links.Links(
                                self = '0', 
                                collection = '0', )
                            ], 
                        id = 56, 
                        account_id = 56, 
                        created_by = '0', 
                        created_on = '0', 
                        payment_date = '0', 
                        payment_id = 56, 
                        paid = 1.337, 
                        line_items = [
                            openapi_client.models.payment_line_item.PaymentLineItem(
                                id = 56, 
                                invoice_id = 56, 
                                fee_schedule_id = 56, 
                                quantity = 56, 
                                filing_fees = 1.337, 
                                service_fees = 1.337, 
                                processing_fees = 1.337, 
                                description = 1.337, 
                                gst = 1.337, 
                                pst = 1.337, 
                                status_code = 'DRAFT', )
                            ], 
                        reference_number = '0', 
                        status_code = 'DRAFT', )
                    ], 
                transactions = [
                    openapi_client.models.transaction.Transaction(
                        _links = [
                            openapi_client.models.links.Links(
                                self = '0', 
                                collection = '0', )
                            ], 
                        id = '0', 
                        client_system_url = '0', 
                        start_time = '0', 
                        end_time = '0', 
                        pay_system_url = '0', 
                        payment_id = 56, 
                        status_code = 'DRAFT', )
                    ], 
                payment_method = '0', 
                status_code = 'DRAFT', 
                updated_by = '0', 
                updated_on = '0'
            )
        else :
            return Payment(
        )

    def testPayment(self):
        """Test Payment"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
