---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "event-json-datafix"
  annotations:
    description: "Scheduled Task to decompress the json_zip column into event_json column in the namex postgres database"
    tags: "cronjob"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "event-json-datafix"
  spec:
    schedule: "* 01 * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "event-json-datafix"
              image: "docker-registry.default.svc:5000/servicebc-ne-tools/event-json-datafix:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                  - name: DATABASE_USERNAME
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql
                  - name: DATABASE_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql
                  - name: DATABASE_NAME
                    valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: postgresql
                  - name: DATABASE_HOST
                    value: 'postgresql'
                  - name: DATABASE_PORT
                    value: '5432'
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "dev"
        },
]