"""empty message

Revision ID: 0b467fe38868
Revises: 
Create Date: 2019-02-19 11:52:06.845688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b467fe38868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synonym', sa.Column('stems_text', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synonym', 'stems_text')
    # ### end Alembic commands ###
