"""empty message

Revision ID: 7c0eea5aec99
Revises: 
Create Date: 2019-02-19 10:12:03.052279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c0eea5aec99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synonym', sa.Column('stems_text', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'synonym', ['stems_text'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synonym', type_='unique')
    op.drop_column('synonym', 'stems_text')
    # ### end Alembic commands ###
