"""empty message

Revision ID: 8c861a947bb2
Revises: 
Create Date: 2019-02-19 12:23:07.850146

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c861a947bb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("synonym", sa.Column("stems_text", sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("synonym", "stems_text")
    # ### end Alembic commands ###
