"""empty message

Revision ID: d8e9c4ee2e74
Revises: 
Create Date: 2019-02-08 09:55:14.154904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8e9c4ee2e74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonym_bak')
    op.drop_table('synonym_audit_bak')
    op.drop_table('synonym_orig')
    op.drop_table('synonym_audit')
    op.alter_column('synonym', 'stems_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.create_unique_constraint(None, 'synonym', ['stems_text'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synonym', type_='unique')
    op.alter_column('synonym', 'stems_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_table('synonym_audit',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('synonym_audit_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('synonym_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synonyms_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('stems_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='synonym_audit_pkey')
    )
    op.create_table('synonym_orig',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synonyms_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('synonym_audit_bak',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('synonym_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('CREATE', 'DELETE', 'UPDATE', name='audit_action'), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synonyms_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('synonym_bak',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synonyms_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('stems_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
