"""empty message

Revision ID: 44d7a2ca511c
Revises: 52c4ed2d1bde
Create Date: 2020-10-20 08:28:47.849160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d7a2ca511c'
down_revision = '52c4ed2d1bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_names', 'auto_analyse_issue_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_names', 'auto_analyse_issue_type',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
