"""empty message

Revision ID: 52c4ed2d1bde
Revises: 888e5e8e54a7
Create Date: 2020-10-06 16:22:36.034011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c4ed2d1bde'
down_revision = '888e5e8e54a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uat_job_results', sa.Column('uat_finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uat_job_results', 'uat_finished')
    # ### end Alembic commands ###
