"""empty message

Revision ID: 888e5e8e54a7
Revises: 
Create Date: 2020-10-06 12:56:21.569859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '888e5e8e54a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uat_job_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('results_sent', sa.Boolean(), nullable=True),
    sa.Column('uat_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uat_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uat_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('choice', sa.Integer(), nullable=True),
    sa.Column('conflict1_num', sa.VARCHAR(length=20), nullable=True),
    sa.Column('conflict1', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('decision_text', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('name_state', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nr_num', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nr_request_type_cd', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nr_state', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nr_submitted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_analyse_issue_text', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('auto_analyse_conflict1', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('auto_analyse_issue_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('auto_analyse_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_analyse_result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('auto_analyse_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_analyse_request_time', sa.Integer(), nullable=True),
    sa.Column('uat_result', sa.String(length=20), nullable=True),
    sa.Column('uat_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uat_job_id'], ['uat_job_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_names')
    op.drop_table('uat_job_results')
    # ### end Alembic commands ###
