"""empty message

Revision ID: 54559c378ea2
Revises: cf65e3c1a6c5
Create Date: 2018-05-30 22:38:05.353210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54559c378ea2'
down_revision = 'cf65e3c1a6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('fax_number', sa.String(length=30), nullable=True),
    sa.Column('email_address', sa.String(length=75), nullable=True),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('client_first_name', sa.String(length=50), nullable=True),
    sa.Column('client_last_name', sa.String(length=50), nullable=True),
    sa.Column('decline_notification_ind', sa.String(length=1), nullable=True),
    sa.Column('addr_line_1', sa.String(length=200), nullable=True),
    sa.Column('addr_line_2', sa.String(length=200), nullable=True),
    sa.Column('addr_line_3', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('postal_cd', sa.String(length=20), nullable=True),
    sa.Column('state_province_cd', sa.String(length=2), nullable=True),
    sa.Column('country_type_cd', sa.String(length=2), nullable=True),
    sa.Column('nr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nr_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    # ### end Alembic commands ###
