"""empty message

Revision ID: a6af81f3d416
Revises: 82e083493064
Create Date: 2018-06-18 12:54:31.972142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6af81f3d416'
down_revision = '82e083493064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_name_system', 'partner_name_type_cd', type_=sa.VARCHAR(length=10))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_name_system', 'partner_name_type_cd', type_=sa.VARCHAR(length=3))
    # ### end Alembic commands ###
