"""empty message

Revision ID: c0f893cd0dee
Revises: b4c1a263798c
Create Date: 2018-05-30 23:45:29.807874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0f893cd0dee'
down_revision = 'b4c1a263798c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_name_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_name_type_cd', sa.String(length=2), nullable=True),
    sa.Column('partner_name_number', sa.String(length=20), nullable=True),
    sa.Column('partner_jurisdiction_type_cd', sa.String(length=3), nullable=True),
    sa.Column('partner_name_date', sa.DateTime(), nullable=True),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('nr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nr_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_name_system')
    # ### end Alembic commands ###
