"""empty message

Revision ID: dfcc6642758a
Revises: b6e02c1b82dd
Create Date: 2018-07-23 13:16:58.678509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcc6642758a'
down_revision = 'b6e02c1b82dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('corp_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'corp_num')
    # ### end Alembic commands ###
