-- noinspection SqlNoDataSourceInspectionForFile

DROP TABLE NAMEX.CONFIGURATION CASCADE CONSTRAINTS;

CREATE TABLE NAMEX.CONFIGURATION
(
  APPLICATION  VARCHAR2(20 BYTE),
  NAME         VARCHAR2(50 BYTE),
  VALUE        VARCHAR2(2000 BYTE),
  DESCRIPTION  VARCHAR2(100 BYTE)
);


CREATE UNIQUE INDEX NAMEX.CONFIGURATION_UK ON NAMEX.CONFIGURATION
(APPLICATION, NAME);


ALTER TABLE NAMEX.CONFIGURATION ADD (
  CONSTRAINT CONFIGURATION_UK
 UNIQUE (APPLICATION, NAME));
