apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    name: ${NAME}
  name: ${NAME}
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: "${NAME}-${TAG}"
    labels:
      name: "${NAME}"
      environment: "${TAG}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: ${NAME}
    template:
      metadata:
        labels:
          deployment: ${NAME}
      spec:
        containers:
          - name: "${NAME}-${TAG}"
            image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${NAME}:${TAG}"
            imagePullPolicy: Always
            ports:
              - containerPort: 9000
                protocol: TCP
            resources:
              limits:
                cpu: 100m
                memory: 1Gi
              requests:
                cpu: 10m
                memory: 512Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            env:
              - name: PG_USER
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: DATABASE_USERNAME
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: DATABASE_PASSWORD
              - name: PG_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: DATABASE_NAME
              - name: PG_HOST
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: DATABASE_HOST
              - name: PG_PORT
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: DATABASE_PORT
              - name: MAX_ROWS
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: MAX_ROWS
              - name: MIN_DELAY_SECONDS
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: MIN_DELAY_SECONDS
              - name: EXPIRES_DAYS
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: EXPIRES_DAYS
              - name: ORA_PORT
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: ORA_PORT
              - name: ORA_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: ORA_DB_NAME
              - name: ORA_HOST
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: ORA_HOST
              - name: ORA_USER
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: ORA_USER
              - name: ORA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${NAME}-${TAG}-secret
                    key: ORA_PASSWORD
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: Recreate
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: nro-update

  - name: TAG
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true

  - name: NAMESPACE
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: f2b77c

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: f2b77c-tools

  - name: IMAGE_REGISTRY
    displayName: Image Registry
    required: true
    description: The image registry of the OpenShift project.
    value: image-registry.openshift-image-registry.svc:5000
