apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: solr-feeder-pipeline
    name: solr-feeder-pipeline
    template: solr-feeder-pipeline
  name: solr-feeder-pipeline
  namespace: servicebc-ne-tools
  resourceVersion: '529523490'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/servicebc-ne-tools/buildconfigs/solr-feeder-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    contextDir: /solr-feeder
    git:
      ref:
      uri: 'https://github.com/kialj876/namex.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
status:
  lastVersion: 1
