---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "nro-update"
  annotations:
    description: "Scheduled Task to update the legacy NRO database"
    tags: "cronjob,nro"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "nro-update"
  spec:
    schedule: "*/10 7-19 * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "nro-update"
              image: "docker-registry.default.svc:5000/servicebc-ne-tools/nro-update-runtime:${ENV_TAG}"
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                  - name: PG_USER
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql
                  - name: PG_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql
                  - name: PG_DB_NAME
                    valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: postgresql
                  - name: PG_HOST
                    value: 'postgresql'
                  - name: PG_PORT
                    value: '5432'
                  - name: MAX_ROWS
                    value: "${MAX_ROWS}"
                  - name: MIN_DELAY_SECONDS
                    value: "${MIN_DELAY_SECONDS}"
                  - name: ORA_PORT
                    valueFrom:
                      secretKeyRef:
                        key: port
                        name: ora-names-secrets
                  - name: ORA_DB_NAME
                    valueFrom:
                      secretKeyRef:
                        key: db_name
                        name: ora-names-secrets
                  - name: ORA_HOST
                    valueFrom:
                      secretKeyRef:
                        key: host
                        name: ora-names-secrets
                  - name: ORA_USER
                    valueFrom:
                      secretKeyRef:
                        key: username
                        name: ora-names-secrets
                  - name: ORA_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: password
                        name: ora-names-secrets
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "test"
        },
        {
          "name": "MAX_ROWS",
          "displayName": "MAX_ROWS",
          "description": "The maximum number of Name Requests to process per job run",
          "required": true,
          "value": "100"
        },
        {
          "name": "MIN_DELAY_SECONDS",
          "displayName": "MIN_DELAY_SECONDS",
          "description": "The minimum amount of time between when the job started and the approve/rejected timestamp of the Name Request",
          "required": true,
          "value": "600"
        },
]
