from .abstract import AnalysisResponseIssue

from .add_descriptive_word import AddDescriptiveWordIssue
from .add_distinctive_word import AddDistinctiveWordIssue
from .check_is_valid import CheckIsValid as CheckIsValidIssue
from .contains_unclassifiable_word import ContainsUnclassifiableWordIssue
from .contains_words_to_avoid import ContainsWordsToAvoidIssue
from .corporate_name_conflict import CorporateNameConflictIssue
from .queue_name_conflict import QueueNameConflictIssue
from .designation_mismatch import DesignationMismatchIssue
from .designation_removal import DesignationRemovalIssue
from .end_designation_more_than_once import EndDesignationMoreThanOnceIssue
from .designation_misplaced import DesignationMisplacedIssue
from .designation_non_existent import DesignationNonExistentIssue
from .incorrect_category import IncorrectCategory as IncorrectCategoryIssue
from .incorrect_year import IncorrectYear as IncorrectYearIssue
from .name_requires_consent import NameRequiresConsentIssue
from .too_many_words import TooManyWordsIssue
from .word_special_use import WordSpecialUse as WordSpecialUseIssue
