from nltk.stem import PorterStemmer

porter = PorterStemmer()
STEM_W = 0.85
SUBS_W = 0.65
OTHER_W = 1.2

EXACT_MATCH = 1.0
HIGH_SIMILARITY = 0.85
MEDIUM_SIMILARITY = 0.71
MINIMUM_SIMILARITY = 0.66

HIGH_CONFLICT_RECORDS = 20
