import datetime

EXACT_MATCH = 1.0
HIGH_SIMILARITY = 0.85
HIGH_CONFLICT_RECORDS = 20

now = datetime.datetime.now()
CURRENT_YEAR = now.year
CURRENT_MONTH = now.month
CURRENT_DAY = now.day
LOWER_LIMIT_TIME = CURRENT_YEAR - 100
UPPER_LIMIT_TIME = CURRENT_YEAR + 10
EXCEPTION_YEARS = [2020]
