"""empty message

Revision ID: 50444de8c77b
Revises: 6e56cd88c725
Create Date: 2018-11-08 11:11:54.120692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50444de8c77b'
down_revision = '6e56cd88c725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'restricted_condition', 'restricted_word_condition', ['cnd_id'], ['cnd_id'])
    op.create_foreign_key(None, 'restricted_word', 'restricted_word_condition', ['word_id'], ['word_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restricted_word', type_='foreignkey')
    op.drop_constraint(None, 'restricted_condition', type_='foreignkey')
    op.drop_table('restricted_view')
    # ### end Alembic commands ###
