"""empty message

Revision ID: 6e56cd88c725
Revises: e0ec817ad276
Create Date: 2018-11-07 11:02:05.123128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e56cd88c725'
down_revision = 'e0ec817ad276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricted_condition',
    sa.Column('cnd_id', sa.Integer(), nullable=False),
    sa.Column('cnd_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('allow_use', sa.VARCHAR(length=1), nullable=True),
    sa.Column('consent_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('consenting_body', sa.VARCHAR(length=195), nullable=True),
    sa.Column('instructions', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('cnd_id')
    )
    op.create_table('restricted_condition_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('cnd_id', sa.Integer(), nullable=True),
    sa.Column('cnd_text', sa.String(length=1000), nullable=True),
    sa.Column('consent_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('consenting_body', sa.VARCHAR(length=195), nullable=True),
    sa.Column('instructions', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('allow_use', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_phrase', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('restricted_word_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('word_phrase', sa.VARCHAR(length=60), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_word_audit')
    op.drop_table('restricted_word')
    op.drop_table('restricted_condition_audit')
    op.drop_table('restricted_condition')
    # ### end Alembic commands ###
