"""empty message

Revision ID: bb55aaafd4db
Revises: 
Create Date: 2018-11-15 11:16:42.258889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb55aaafd4db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_reason',
    sa.Column('dr_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('dr_id')
    )
    op.create_table('restricted_link_word_condition',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('cnd_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('cnd_id', 'word_id')
    )
    op.create_table('restricted_link_word_condition_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('cnd_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_view',
    sa.Column('word_phrase', sa.VARCHAR(length=60), nullable=True),
    sa.Column('cnd_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('consent_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('consenting_body', sa.VARCHAR(length=195), nullable=True),
    sa.Column('instructions', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('allow_use', sa.VARCHAR(length=1), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('cnd_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('word_id', 'cnd_id')
    )
    op.alter_column('synonym', 'synonyms_text',
               existing_type=sa.VARCHAR(length=1500),
               nullable=False)
    op.alter_column('synonym_audit', 'synonym_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synonym_audit', 'synonym_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('synonym', 'synonyms_text',
               existing_type=sa.VARCHAR(length=1500),
               nullable=True)
    op.drop_table('restricted_view')
    op.drop_table('restricted_link_word_condition_audit')
    op.drop_table('restricted_link_word_condition')
    op.drop_table('decision_reason')
    # ### end Alembic commands ###
