# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ContactInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'first_name': 'str',
        'last_name': 'str',
        'address': 'str',
        'city': 'str',
        'province': 'str',
        'postal_code': 'str'
    }

    attribute_map = {
        'first_name': 'firstName',
        'last_name': 'lastName',
        'address': 'address',
        'city': 'city',
        'province': 'province',
        'postal_code': 'postalCode'
    }

    def __init__(self, first_name=None, last_name=None, address=None, city=None, province=None, postal_code=None, local_vars_configuration=None):  # noqa: E501
        """ContactInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._first_name = None
        self._last_name = None
        self._address = None
        self._city = None
        self._province = None
        self._postal_code = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if address is not None:
            self.address = address
        if city is not None:
            self.city = city
        if province is not None:
            self.province = province
        if postal_code is not None:
            self.postal_code = postal_code

    @property
    def first_name(self):
        """Gets the first_name of this ContactInfo.  # noqa: E501

        Contact first name  # noqa: E501

        :return: The first_name of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ContactInfo.

        Contact first name  # noqa: E501

        :param first_name: The first_name of this ContactInfo.  # noqa: E501
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this ContactInfo.  # noqa: E501

        Contact last name  # noqa: E501

        :return: The last_name of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this ContactInfo.

        Contact last name  # noqa: E501

        :param last_name: The last_name of this ContactInfo.  # noqa: E501
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def address(self):
        """Gets the address of this ContactInfo.  # noqa: E501

        Addres line 1  # noqa: E501

        :return: The address of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ContactInfo.

        Addres line 1  # noqa: E501

        :param address: The address of this ContactInfo.  # noqa: E501
        :type address: str
        """

        self._address = address

    @property
    def city(self):
        """Gets the city of this ContactInfo.  # noqa: E501

        City  # noqa: E501

        :return: The city of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this ContactInfo.

        City  # noqa: E501

        :param city: The city of this ContactInfo.  # noqa: E501
        :type city: str
        """

        self._city = city

    @property
    def province(self):
        """Gets the province of this ContactInfo.  # noqa: E501

        Province  # noqa: E501

        :return: The province of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province):
        """Sets the province of this ContactInfo.

        Province  # noqa: E501

        :param province: The province of this ContactInfo.  # noqa: E501
        :type province: str
        """

        self._province = province

    @property
    def postal_code(self):
        """Gets the postal_code of this ContactInfo.  # noqa: E501

        Postal Code  # noqa: E501

        :return: The postal_code of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this ContactInfo.

        Postal Code  # noqa: E501

        :param postal_code: The postal_code of this ContactInfo.  # noqa: E501
        :type postal_code: str
        """

        self._postal_code = postal_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContactInfo):
            return True

        return self.to_dict() != other.to_dict()
