# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Fee(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'filing_type_code': 'str',
        'filing_type': 'str',
        'filing_fees': 'int',
        'service_fees': 'int',
        'processing_fees': 'int',
        'tax': 'list[Tax]'
    }

    attribute_map = {
        'filing_type_code': 'filingTypeCode',
        'filing_type': 'filingType',
        'filing_fees': 'filingFees',
        'service_fees': 'serviceFees',
        'processing_fees': 'processingFees',
        'tax': 'tax'
    }

    def __init__(self, filing_type_code=None, filing_type=None, filing_fees=None, service_fees=None, processing_fees=None, tax=None, local_vars_configuration=None):  # noqa: E501
        """Fee - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._filing_type_code = None
        self._filing_type = None
        self._filing_fees = None
        self._service_fees = None
        self._processing_fees = None
        self._tax = None
        self.discriminator = None

        if filing_type_code is not None:
            self.filing_type_code = filing_type_code
        if filing_type is not None:
            self.filing_type = filing_type
        if filing_fees is not None:
            self.filing_fees = filing_fees
        if service_fees is not None:
            self.service_fees = service_fees
        if processing_fees is not None:
            self.processing_fees = processing_fees
        if tax is not None:
            self.tax = tax

    @property
    def filing_type_code(self):
        """Gets the filing_type_code of this Fee.  # noqa: E501

        Filing Type Code  # noqa: E501

        :return: The filing_type_code of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._filing_type_code

    @filing_type_code.setter
    def filing_type_code(self, filing_type_code):
        """Sets the filing_type_code of this Fee.

        Filing Type Code  # noqa: E501

        :param filing_type_code: The filing_type_code of this Fee.  # noqa: E501
        :type filing_type_code: str
        """

        self._filing_type_code = filing_type_code

    @property
    def filing_type(self):
        """Gets the filing_type of this Fee.  # noqa: E501

        Filing Type  # noqa: E501

        :return: The filing_type of this Fee.  # noqa: E501
        :rtype: str
        """
        return self._filing_type

    @filing_type.setter
    def filing_type(self, filing_type):
        """Sets the filing_type of this Fee.

        Filing Type  # noqa: E501

        :param filing_type: The filing_type of this Fee.  # noqa: E501
        :type filing_type: str
        """

        self._filing_type = filing_type

    @property
    def filing_fees(self):
        """Gets the filing_fees of this Fee.  # noqa: E501

        Fees for filing  # noqa: E501

        :return: The filing_fees of this Fee.  # noqa: E501
        :rtype: int
        """
        return self._filing_fees

    @filing_fees.setter
    def filing_fees(self, filing_fees):
        """Sets the filing_fees of this Fee.

        Fees for filing  # noqa: E501

        :param filing_fees: The filing_fees of this Fee.  # noqa: E501
        :type filing_fees: int
        """

        self._filing_fees = filing_fees

    @property
    def service_fees(self):
        """Gets the service_fees of this Fee.  # noqa: E501

        Applicable service fees  # noqa: E501

        :return: The service_fees of this Fee.  # noqa: E501
        :rtype: int
        """
        return self._service_fees

    @service_fees.setter
    def service_fees(self, service_fees):
        """Sets the service_fees of this Fee.

        Applicable service fees  # noqa: E501

        :param service_fees: The service_fees of this Fee.  # noqa: E501
        :type service_fees: int
        """

        self._service_fees = service_fees

    @property
    def processing_fees(self):
        """Gets the processing_fees of this Fee.  # noqa: E501

        Applicable processing fees  # noqa: E501

        :return: The processing_fees of this Fee.  # noqa: E501
        :rtype: int
        """
        return self._processing_fees

    @processing_fees.setter
    def processing_fees(self, processing_fees):
        """Sets the processing_fees of this Fee.

        Applicable processing fees  # noqa: E501

        :param processing_fees: The processing_fees of this Fee.  # noqa: E501
        :type processing_fees: int
        """

        self._processing_fees = processing_fees

    @property
    def tax(self):
        """Gets the tax of this Fee.  # noqa: E501


        :return: The tax of this Fee.  # noqa: E501
        :rtype: list[Tax]
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """Sets the tax of this Fee.


        :param tax: The tax of this Fee.  # noqa: E501
        :type tax: list[Tax]
        """

        self._tax = tax

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Fee):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Fee):
            return True

        return self.to_dict() != other.to_dict()
