# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PaymentInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'method_of_payment': 'str'
    }

    attribute_map = {
        'method_of_payment': 'methodOfPayment'
    }

    def __init__(self, method_of_payment=None, local_vars_configuration=None):  # noqa: E501
        """PaymentInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._method_of_payment = None
        self.discriminator = None

        if method_of_payment is not None:
            self.method_of_payment = method_of_payment

    @property
    def method_of_payment(self):
        """Gets the method_of_payment of this PaymentInfo.  # noqa: E501

        Method of payment  # noqa: E501

        :return: The method_of_payment of this PaymentInfo.  # noqa: E501
        :rtype: str
        """
        return self._method_of_payment

    @method_of_payment.setter
    def method_of_payment(self, method_of_payment):
        """Sets the method_of_payment of this PaymentInfo.

        Method of payment  # noqa: E501

        :param method_of_payment: The method_of_payment of this PaymentInfo.  # noqa: E501
        :type method_of_payment: str
        """

        self._method_of_payment = method_of_payment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PaymentInfo):
            return True

        return self.to_dict() != other.to_dict()
