"""empty message

Revision ID: 00952c5a4109
Revises: b0fc67a096fe
Create Date: 2021-06-02 11:24:29.085137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00952c5a4109'
down_revision = 'b0fc67a096fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('name_search', sa.String(length=3078), nullable=True))
    op.create_index(op.f('ix_requests_name_search'), 'requests', ['name_search'], unique=False)
    # ### end Alembic commands ###
    conn = op.get_bind()
    # add all names to nameSearch column
    cd_exists = conn.execute("select * from states where cd='PENDING_PAYMENT'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_name_search'), table_name='requests')
    op.drop_column('requests', 'name_search')
    # ### end Alembic commands ###
