"""empty message

Revision ID: 07563e18d763
Revises: 9d48257d000e
Create Date: 2020-10-19 17:40:46.249197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07563e18d763'
down_revision = '9d48257d000e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('names', 'clean_name')
    op.add_column('payments', sa.Column('payment_note', sa.String(length=100), nullable=True))
    op.add_column('requests', sa.Column('checked_out_by', sa.String(length=64), nullable=True))
    op.add_column('requests', sa.Column('checked_out_dt', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_requests_checked_out_by'), 'requests', ['checked_out_by'], unique=False)
    op.create_index(op.f('ix_requests_checked_out_dt'), 'requests', ['checked_out_dt'], unique=False)
    op.drop_column('requests', 'payment_id')
    op.drop_column('requests', 'payment_completion_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('payment_completion_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('payment_id', sa.VARCHAR(length=4096), autoincrement=False, nullable=True))

    op.drop_index(op.f('ix_requests_checked_out_dt'), table_name='requests')
    op.drop_index(op.f('ix_requests_checked_out_by'), table_name='requests')
    op.drop_column('requests', 'checked_out_dt')
    op.drop_column('requests', 'checked_out_by')
    op.drop_column('payments', 'payment_note')
    op.add_column('names', sa.Column('clean_name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
