"""empty message

Revision ID: 0aebf0835b06
Revises: 5b30946cd550
Create Date: 2020-04-29 11:56:43.217078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0aebf0835b06'
down_revision = '5b30946cd550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('home_juris_num', sa.String(length=40), nullable=True))
    op.add_column('requests', sa.Column('trade_mark', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'trade_mark')
    op.drop_column('requests', 'home_juris_num')
    # ### end Alembic commands ###
