"""payment_receipt_furnished

Revision ID: 0d8662dfb68a
Revises: 20285314989a
Create Date: 2021-01-11 17:17:20.619141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8662dfb68a'
down_revision = '20285314989a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('furnished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'furnished')
    # ### end Alembic commands ###
