"""empty message

Revision ID: 1246e7c47388
Revises: a4f3edc39b9d
Create Date: 2018-10-01 15:06:11.765816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1246e7c47388'
down_revision = 'a4f3edc39b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_name_system', sa.Column('requested', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_name_system', 'requested')
    # ### end Alembic commands ###
