"""empty message

Revision ID: 20285314989a
Revises: 8b99aacb139b
Create Date: 2021-01-04 12:18:42.722315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20285314989a'
down_revision = '8b99aacb139b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_action', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_action')
    # ### end Alembic commands ###
