"""empty message

Revision ID: 21b272432e62
Revises: 31043289e39a
Create Date: 2018-08-13 02:13:12.961908

Add the following tables and sequences for use in NRO Updater:

nro_names_sync_job (table)
nro_names_sync_job_detail (table)
nro_job_seq (sequence)

The table generation code is auto-generated but the sequence is manually added.

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '21b272432e62'
down_revision = '31043289e39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nro_names_sync_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_cd', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nro_names_sync_job_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('nr_num', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(sa.schema.CreateSequence(sa.schema.Sequence("nro_job_seq"), if_not_exists=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nro_names_sync_job_detail')
    op.drop_table('nro_names_sync_job')

    op.execute(sa.schema.DropSequence(sa.schema.Sequence("nro_job_seq")))

    # ### end Alembic commands ###
