"""empty message

Revision ID: 229257754f99
Revises: ffcd16e0e2f5
Create Date: 2019-03-08 16:20:19.900092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229257754f99'
down_revision = 'ffcd16e0e2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('names', sa.Column('corp_num', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('names', 'corp_num')
    # ### end Alembic commands ###
