"""empty message

Revision ID: 490cecca90fc
Revises: bff2c29281fa
Create Date: 2020-03-20 11:52:25.996687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '490cecca90fc'
down_revision = 'bff2c29281fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # request model
    op.add_column('requests', sa.Column('consent_dt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('entity_type_cd', sa.String(length=10), nullable=True))
    op.add_column('requests', sa.Column('payment_completion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('payment_id', sa.String(length=4096), nullable=True))
    op.add_column('requests', sa.Column('request_action_cd', sa.String(length=10), nullable=True))
    op.add_column('requests', sa.Column('source', sa.String(length=15), nullable=True))

    #name model
    op.add_column('names', sa.Column('clean_name', sa.String(length=1024), nullable=True))
    op.add_column('names', sa.Column('name_type_cd', sa.String(length=10), server_default='CO', nullable=True))
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'source')
    op.drop_column('requests', 'request_action_cd')
    op.drop_column('requests', 'payment_id')
    op.drop_column('requests', 'payment_completion_date')
    op.drop_column('requests', 'entity_type_cd')
    op.drop_column('requests', 'consent_dt')
    # ### end Alembic commands ###
