"""hotjar_tracking

Revision ID: 5cdf7f1bbd6f
Revises: d788fb44fa0e
Create Date: 2022-04-01 11:02:46.044381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdf7f1bbd6f'
down_revision = 'd788fb44fa0e'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('hotjar_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nr_id', sa.Integer(), nullable=True),
    sa.Column('hotjar_user', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotjar_tracking')

