"""perf_indexes

Revision ID: 5e1d992e46d5
Revises: 73d051437ad0
Create Date: 2018-11-08 20:54:59.981331

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5e1d992e46d5'
down_revision = '73d051437ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.create_index(op.f('ix_applicants_nr_id'), 'applicants', ['nr_id'], unique=False)
    op.create_index(op.f('ix_comments_nr_id'), 'comments', ['nr_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_names_nr_id'), 'names', ['nr_id'], unique=False)
    op.create_index(op.f('ix_partner_name_system_nr_id'), 'partner_name_system', ['nr_id'], unique=False)
    op.create_index(op.f('ix_requests_furnished'), 'requests', ['furnished'], unique=False)
    op.create_index(op.f('ix_requests_state_cd'), 'requests', ['state_cd'], unique=False)
    op.create_index(op.f('ix_requests_submitted_date'), 'requests', ['submitted_date'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    op.execute('CREATE INDEX ' + op.f('ix_names_name')
               + ' ON names USING btree'
               + ' (name COLLATE pg_catalog."default" varchar_pattern_ops)'
               + ' TABLESPACE pg_default;'
               )

    op.execute('ALTER TABLE names CLUSTER ON '
               + op.f('ix_names_nr_id'))

    op.execute('ALTER TABLE comments CLUSTER ON '
               + op.f('ix_comments_nr_id'))

    op.execute('ALTER TABLE partner_name_system CLUSTER ON '
               + op.f('ix_partner_name_system_nr_id'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_submitted_date'), table_name='requests')
    op.drop_index(op.f('ix_requests_state_cd'), table_name='requests')
    op.drop_index(op.f('ix_requests_furnished'), table_name='requests')
    op.drop_index(op.f('ix_partner_name_system_nr_id'), table_name='partner_name_system')
    op.drop_index(op.f('ix_names_nr_id'), table_name='names')
    op.drop_index(op.f('ix_names_name'), table_name='names')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_nr_id'), table_name='comments')
    op.drop_index(op.f('ix_applicants_nr_id'), table_name='applicants')
