"""create synonyms table

Revision ID: 739471406664
Revises: 0d8662dfb68a
Create Date: 2021-01-18 11:58:11.070023

"""
from alembic import op
import sqlalchemy as sa
import pandas as pd
import os
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '739471406664'
down_revision = '0d8662dfb68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    current_dir = os.getcwd()
    synonyms_path = os.getenv('SYNONYMS_DATA_FILE')
    synonyms_file = os.path.abspath(os.path.join(os.path.join(current_dir, synonyms_path)))

    columns = ['id', 'category', 'synonyms_text', 'stems_text', 'comment', 'enabled']
    dict_from_csv = pd.read_csv(synonyms_file, header=None, index_col=0, names=columns)  # .to_dict('records')
    dict_from_csv.enabled = True if [dict_from_csv.enabled == 't'] else False
    dict_from_csv = dict_from_csv.to_dict('records')

    synonym_table = op.create_table('synonym',
                                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                                    sa.Column('category', sa.String(length=100)),
                                    sa.Column('synonyms_text', sa.String(length=1000), unique=True, nullable=False),
                                    sa.Column('stems_text', sa.String(length=1000), nullable=False),
                                    sa.Column('comment', sa.String(length=1000)),
                                    sa.Column('enabled', sa.Boolean(), default=True),
                                    sa.PrimaryKeyConstraint('id')
                                    )
    op.bulk_insert(
        synonym_table,
        dict_from_csv
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonym')
    # ### end Alembic commands ###


def replace_enabled(enabled):
    enabled_new = True if enabled == 't' else False
    return enabled_new
