"""empty message

Revision ID: 73d051437ad0
Revises: 1246e7c47388
Create Date: 2018-10-30 14:12:04.404367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '73d051437ad0'
down_revision = '1246e7c47388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    pass
    op.create_index('requests_completed_updated_at_index',
                    'requests', [text('last_update DESC NULLS LAST')],
                    postgresql_where=sa.text("requests.state_cd IN ('APPROVED', 'REJECTED', 'CONDITIONAL')"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index('requests_completed_updated_at_index')
