"""empty message

Revision ID: 75b6e6ecfde9
Revises: d06d24498377
Create Date: 2018-12-01 19:19:17.246718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b6e6ecfde9'
down_revision = 'd06d24498377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('prev_state_cd', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'prev_state_cd')
    # ### end Alembic commands ###
