"""empty message

Revision ID: 8a9044342457
Revises: 69b15a47f334
Create Date: 2018-06-13 12:56:08.768984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9044342457'
down_revision = '69b15a47f334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    decision_reason_table = op.create_table('decision_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        decision_reason_table,
        [
            {'id': 3, 'name': 'Amend Real Estate ', 'reason': '***Name Amended To Allow Acceptance By Real Estate Council***'},
            {'id': 4, 'name': 'Amend ', 'reason': '*** Name Amended To Allow Acceptance ***'},
            {'id': 5, 'name': 'Assumed Name', 'reason': 'Assumed Name A Foreign Entity Whose Name Has Been Rejected For Use In Bc, May Register In Bc Under An Assumed Name.'},
            {'id': 6, 'name': 'Assumed Yes ', 'reason': 'A Foreign Entity That Is Registering In British Columbia As An Extraprovincial Company And Adopting An Assumed Name Must Provide The Registrar With A Covering Letter Attaching An Undertaking To Carry On Business Under The Assumed Name.  Sample Working For The Undertaking Can Be Found On Page 34 Of The Information For Registration Of An Extraprovincial Company In British Columbia   Information Package And Also In The Online Help Text At Www.Corporateonline.Gob Please Fax The Letter Containing The Undertaking To The Attention Of The Corporations Unit, Bc Registry Services (Fax Number:250 356-8923).'},
            {'id': 7, 'name': 'Cancel Refund ', 'reason': 'Reservation Not Required - Fees Refunded.'},
            {'id': 8, 'name': 'Char ', 'reason': 'No Provision For Special Characters'},
            {'id': 9, 'name': 'Conditions ', 'reason': 'This Name Reservation Has A Condition That Must Be Met.  You Will Need To Contact This Office So Registry Staff Can Release The Condition Before You Incorporate Or Register.'},
            {'id': 10, 'name': 'Consent Firms ', 'reason': '** Written And Signed Consent Must Be Received Before You Can Register, Please Email To Consent.Letters@Gov.Bc.Ca**'},
            {'id': 11, 'name': 'Consent Incorp ', 'reason': '** Written And Signed Consent Must Be Received Before You Can Incorporate, Please Email To Consent.Letters@Gov.Bc.Ca **'},
            {'id': 12, 'name': 'Consent Prop', 'reason': 'Consent Required If Not General Partner/Proprietor'},
            {'id': 13, 'name': 'Continuation Soc: ', 'reason': 'Once The Name Of The Not For Profit Corporation Has Been Approved The Society Must Submit A Letter Authorizing The Continuation From Its Current Jurisdiction. This Authorization Must Be Submitted To The  Registrar At The Time Of Filing The Location For Continuation In. You Must Include The Name Reservation Number And If The Society Is Currently Registered In Bc As An Extraprovincial Non-Share Corporation, Include The Current Bc Registration Number. Please Review The Incions At Www.Bcregistry Services.Gov.Bc.Ca For Complete Information.'},
            {'id': 14, 'name': 'Continuation', 'reason': 'Once The Name Of The Corporation Has Been Approved, The Corporation Must Submit A Letter Authorizing The Continuation From The Corporation''S Home Jurisdiction. This Authorization Must Be Submitted To The Registrar Prior To Filing The Application For Continuation In. You Must Include The Name Reservation Number And, If The Corporation Is Currently Registered In Bc As An Extraprovincial Company, Please Include The B.C. Registration Number. Email The Consent To Consent.Letters@Gov.Bc.Ca Or Fax To (250)356-8923.  '},
            {'id': 15, 'name': 'Criteria', 'reason': 'Must Meet Bc Criteria'},
            {'id': 16, 'name': 'Designation – Society', 'reason': 'Must Use Society, Association Or Foundation In Name'},
            {'id': 17, 'name': 'Diploma', 'reason': ' "Requires Copy Of Diploma Conferring Title. Email To Consent.Letters@Gov.Bc.Ca."'},
            {'id': 18, 'name': 'Distinguishing', 'reason': 'Requires Distinguishing Term '},
            {'id': 19, 'name': 'Dupresto', 'reason': 'Check Current Reservation Again/Fees Refunded'},
            {'id': 20, 'name': 'Either', 'reason': ' "Requires Either Further Distinctive Or Descriptive Element."'},
            {'id': 21, 'name': 'Existing Company', 'reason': 'After Existing Company Changes Names Or Dissolves'},
            {'id': 22, 'name': 'Extra:  ?', 'reason': ''},
            {'id': 23, 'name': 'Farmers Institute', 'reason': 'Use Of This Term Is Administered By The Ministry Of Agriculture Farmers And Womens Institutes Act.  Please Contact The Superintendent Of Farmers Institutes At Or 1-888-221-7141. '},
            {'id': 24, 'name': 'Federal Refund', 'reason': 'Reservation Not Required For Federal Registration In Bc - Fees Refunded'},
            {'id': 25, 'name': 'Fees', 'reason': 'Entered 2X/Fees Refunded'},
            {'id': 26, 'name': 'Final Res', 'reason': '****Final Reservation*********'},
            {'id': 27, 'name': 'First Name', 'reason': 'Require Clients First Name Or Initials Before The Surname Or A Descriptive Word After.'},
            {'id': 28, 'name': 'Init', 'reason': '“Require A At Least 2 Initials"'},
            {'id': 29, 'name': 'Interrupt', 'reason': 'Name Approval Results Were Updated Due To A System Interruption.'},
            {'id': 30, 'name': 'Iof:  ?', 'reason': ''},
            {'id': 31, 'name': 'Llc Xpro Reg', 'reason': 'The Filing Of Your Llc Registration Cannot Be Completed Online And Must Be Completed By Submitting Form 33 Extrap Provincial Registration, Form 1 Request For A Business Number And A Certified Certificate If Of Status From The Home Jurisdiction To The Corporate Registry For Filing.”'},
            {'id': 32, 'name': 'Llc Change Of Name', 'reason': 'The Filing Of Your Llc Change Of Name Cannot Be Completed Online And Must Be Completed By Submitting Form 37 Notice Of Change Of Name And A Certified Certificate Of Status From The Home Jurisdiction To The Corporate Registry For Filing. '},
            {'id': 33, 'name': 'New Macro', 'reason': '“New Macro Test”'},
            {'id': 34, 'name': 'No Consent', 'reason': 'Consent As Indicated Is Not Required.'},
            {'id': 35, 'name': 'Nro:  ?', 'reason': ''},
            {'id': 36, 'name': 'Number Issue', 'reason': 'Numbers Issued At Time Of Incorporation'},
            {'id': 37, 'name': 'Numbered', 'reason': 'Not Required For Numbered Company '},
            {'id': 38, 'name': 'Offensive', 'reason': 'Could Be Offensive To Some'},
            {'id': 39, 'name': 'Only Change Name', 'reason': 'Only After Existing Company Has Changed Its Name, Amalgamated Or Dissolved.'},
            {'id': 40, 'name': 'Out Of Jurisdiction', 'reason': 'Unable To Register In Bc, Please Refer To The Partnership Regulation, Section 1, '},
            {'id': 41, 'name': 'Outside Canada Xpro', 'reason': 'A Current Certificate Of Status From The Home Jurisdiction Must Be Submitted To The Corporate Registry By Email To Consent.Letters@Gov.Bc.Ca Prior To Registering The Extraprovincial Company Online At Www.Corporateonline.Gov.Bc.Ca.  You Must Include The Name Reservation Number On Your Correspondence.'},
            {'id': 42, 'name': 'Proprietorship', 'reason': '*** Allowed For Proprietorship/Partnership Name Only ***'},
            {'id': 43, 'name': 'Protocol', 'reason': 'Name Declined By Provincial Protocol Office - Call Our Office For Suggested Options And A Free Search'},
            {'id': 44, 'name': 'Society', 'reason': 'Term Restricted To Non-Profit Use Only'},
            {'id': 45, 'name': 'Spell', 'reason': 'Spelling Of Amended Call If Original Is Correct'},
            {'id': 46, 'name': 'Superceded', 'reason': 'Superceded By Incorporation Request - Call For Free Search'},
            {'id': 47, 'name': 'Tm', 'reason': 'Require A Letter Of Consent From Trademark Holder Or Franchisor.  Please Email To Consent.Letters@Gov.Bc.Ca'},
            {'id': 48, 'name': 'Tribal', 'reason': 'Require A Letter Of Consent From Tribal Authority.  Please Email To Consent.Letters@Gov.Bc.Ca'},
            {'id': 49, 'name': 'Ulc Cont In', 'reason': 'After Approval Of The Name Of The Unlimited Liability Corporation Letter Authorizing The Continuation From The Corporation''S Home Jurisdiction Must Be Submitted To The Registrar Prior To Filing The Application For Continuing A Foreign Unlimited Liability Corporation Into British Columbia.  “Include The Name Reservation Number And, If The Corporation Is Currently Registered In Bc As An Extraprovincial Company, The Bc Registration Number.  As Well, An Alberta Unlimited Liability Corporation Must Provide To The Registrar In Addition To The Jurisdiction "  "Authorization, A Director Affidavit Or Certified Copy Of The Court Order From The Home Jurisdiction Approving The Continuation.  Refer To Section 23.1 Of The Business Corporation Regulations. Please Provide A Telephone Number Or E-Mail Address For Notification.  Complete Instructions Are" " At:  Www.Corporateonline.Gov.Bc.Ca'},
            {'id': 50, 'name': 'Xpro', 'reason': '***Extrap -Provincial Registration Only***'},
            {'id': 51, 'name': 'Year', 'reason': 'Year Must Be Year Of Incorporation/Reg Registration/Incorporation/Corporate Name   Change'},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_reason')
    # ### end Alembic commands ###

