"""add_idp_userid_to_users

Revision ID: 9d5d703de794
Revises: 5cdf7f1bbd6f
Create Date: 2022-11-22 09:40:27.699006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5d703de794'
down_revision = '5cdf7f1bbd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idp_userid', sa.String()))
    #op.drop_constraint('users_sub_key', 'users', type_='unique')
    #op.create_unique_constraint('users_idp_userid_key', 'users', ['idp_userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('users_sub_key', 'users', ['sub'])
    #op.drop_constraint('users_idp_userid_key', 'users', ['idp_userid'])
    op.drop_column('users', 'idp_userid')
    # ### end Alembic commands ###
