"""empty message

Revision ID: a4f3edc39b9d
Revises: df796d2e6d4f
Create Date: 2018-09-29 16:11:14.000301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f3edc39b9d'
down_revision = 'df796d2e6d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nro_names_sync_job_detail', sa.Column('error_msg', sa.String(length=1000), nullable=True))
    op.add_column('nro_names_sync_job_detail', sa.Column('success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nro_names_sync_job_detail', 'success')
    op.drop_column('nro_names_sync_job_detail', 'error_msg')
    # ### end Alembic commands ###
