"""empty message

Revision ID: add_decision_fields_to_name
Revises: add_two_decision_reasons
Create Date: 2018-06-25 10:37:58.915817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_decision_fields_to_name'
down_revision = 'add_two_decision_reasons'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('names', sa.Column('conflict1', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('conflict2', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('conflict3', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('conflict1_num', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('conflict2_num', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('conflict3_num', sa.String(length=250), nullable=True))
    op.add_column('names', sa.Column('decision_text', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('names', 'decision_text')
    op.drop_column('names', 'conflict3_num')
    op.drop_column('names', 'conflict2_num')
    op.drop_column('names', 'conflict1_num')
    op.drop_column('names', 'conflict3')
    op.drop_column('names', 'conflict2')
    op.drop_column('names', 'conflict1')
    # ### end Alembic commands ###
