"""empty message

Revision ID: b0fc67a096fe
Revises: 0d8662dfb68a
Create Date: 2021-05-05 14:24:03.870443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fc67a096fe'
down_revision = '0d8662dfb68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('searchColumns', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'searchColumns')
    # ### end Alembic commands ###
