"""empty message

Revision ID: b29e6d35146f
Revises: 28da946c5e79
Create Date: 2018-05-03 13:27:18.943840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b29e6d35146f'
down_revision = '28da946c5e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('nro_updated', sa.String(length=1), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('requests', 'nro_updated')
    # ### end Alembic commands ###
