"""empty message

Revision ID: b6e02c1b82dd
Revises: add_restricted_word_tables
Create Date: 2018-07-10 21:03:22.152573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e02c1b82dd'
down_revision = 'add_restricted_word_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('nro_last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'nro_last_update')
    # ### end Alembic commands ###
