"""empty message

Revision ID: bff2c29281fa
Revises: d21d3839c096
Create Date: 2020-01-31 12:14:00.263206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff2c29281fa'
down_revision = 'd21d3839c096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonym',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms_text', sa.String(length=1000), nullable=False),
    sa.Column('stems_text', sa.String(length=1000), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('synonyms_text')
    )
    op.create_table('synonym_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('synonym_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms_text', sa.String(length=1000), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('synonym_audit')
    op.drop_table('synonym')

    # ### end Alembic commands ###
