"""empty message

Revision ID: d06d24498377
Revises: 5e1d992e46d5
Create Date: 2018-11-15 15:27:08.473426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d24498377'
down_revision = '5e1d992e46d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column('requests', sa.Column('priority_date', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_column('requests', 'priority_date')
