"""empty message

Revision ID: d788fb44fa0e
Revises: 0be658f07ac6
Create Date: 2022-03-14 10:41:16.459011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd788fb44fa0e'
down_revision = '0be658f07ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_nr_id'), 'events', ['nr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_nr_id'), table_name='events')
    # ### end Alembic commands ###
