"""empty message

Revision ID: ffcd16e0e2f5
Revises: 21b953f6b653
Create Date: 2019-02-22 15:42:29.801061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcd16e0e2f5'
down_revision = '21b953f6b653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_reason_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('dr_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_condition_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('cnd_id', sa.Integer(), nullable=True),
    sa.Column('consenting_body', sa.VARCHAR(length=195), nullable=True),
    sa.Column('words', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('cnd_text', sa.String(length=1000), nullable=True),
    sa.Column('instructions', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('consent_required', sa.Boolean(), nullable=True),
    sa.Column('allow_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_word_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rc_consenting_body', sa.VARCHAR(length=195), nullable=True),
    sa.Column('rc_words', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('rc_condition_text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('rc_instructions', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('rc_consent_required', sa.Boolean(), nullable=True),
    sa.Column('rc_allow_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_word_condition')
    op.drop_table('restricted_condition_audit')
    op.drop_table('decision_reason_audit')
    # ### end Alembic commands ###
