---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "nro-extractor"
  annotations:
    description: "Scheduled Task to update the legacy NRO database"
    tags: "cronjob,nro"
objects:
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "nro-extractor"
  spec:
    concurrencyPolicy: "Forbid"
    schedule: "*/1 * * * *"
    suspend: false
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: "nro-extractor"
              image: "docker-registry.default.svc:5000/servicebc-ne-tools/nro-extractor-runtime:${ENV_TAG}"
              imagePullPolicy: Always
              args:
              - /bin/sh
              - -c
              - cd /opt/app-root/src; ./run.sh
              env:
                  - name: PG_USER
                    valueFrom:
                      secretKeyRef:
                        key: database-user
                        name: postgresql-${ENV_TAG}
                  - name: PG_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: database-password
                        name: postgresql-${ENV_TAG}
                  - name: PG_NAME
                    valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: postgresql
                  - name: PG_HOST
                    value: 'postgresql-${ENV_TAG}'
                  - name: PG_PORT
                    value: '5432'
                  - name: MAX_ROWS
                    value: "${MAX_ROWS}"
                  - name: NRO_SERVICE_ACCOUNT
                    value: "${NRO_SERVICE_ACCOUNT}"
                  - name: NRO_PORT
                    valueFrom:
                      secretKeyRef:
                        key: port
                        name: namex-nro-services
                  - name: NRO_DB_NAME
                    valueFrom:
                      secretKeyRef:
                        key: db_name
                        name: namex-nro-services
                  - name: NRO_HOST
                    valueFrom:
                      secretKeyRef:
                        key: host
                        name: namex-nro-services
                  - name: NRO_USER
                    valueFrom:
                      secretKeyRef:
                        key: username
                        name: namex-nro-services
                  - name: NRO_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: password
                        name: namex-nro-services
            restartPolicy: "Never"
            concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "test"
        },
        {
          "name": "MAX_ROWS",
          "displayName": "MAX_ROWS",
          "description": "The maximum number of Name Requests to process per job run",
          "required": true,
          "value": "100"
        },
        {
          "name": "NRO_SERVICE_ACCOUNT",
          "displayName": "NRO_SERVICE_ACCOUNT",
          "description": "The username of the service account",
          "required": true,
          "value": "nro_service_account"
        },
]
