//
// Copyright © 2018 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//JENKINS DEPLOY ENVIRONMENT VARIABLES:
// - JENKINS_JAVA_OVERRIDES  -Dhudson.model.DirectoryBrowserSupport.CSP= -Duser.timezone=America/Vancouver
//   -> user.timezone : set the local timezone so logfiles report correxct time
//   -> hudson.model.DirectoryBrowserSupport.CSP : removes restrictions on CSS file load, thus html pages of test reports are displayed pretty
//   See: https://docs.openshift.com/container-platform/3.9/using_images/other_images/jenkins.html for a complete list of JENKINS env vars

// define constants
def BUILDCFG_BASE ='namex-api-base'
def IMAGE_BASE_NAME = 'namex-api-base'
def BUILDCFG_RUNTIME ='namex-api-runtime'
def IMAGE_RUNTIME_NAME = 'namex-api-runtime'
def DEV_DEPLOYMENT_NAME = 'namex-api'
def DEV_TAG_NAME = 'dev'
def DEV_NS = 'servicebc-ne-dev'
def TST_DEPLOYMENT_NAME = 'namex-api'
def TST_TAG_NAME = 'test'
def TST_BCK_TAG_NAME = 'test-previous'
def TST_NS = 'servicebc-ne-test'
def PROD_DEPLOYMENT_NAME = 'namex-api'
def PROD_TAG_NAME = 'prod'
def PROD_BCK_TAG_NAME = 'prod-previous'
def PROD_NS = 'namex-api-prod'

def GIT_BRANCH_NAME = ("${env.JOB_BASE_NAME}".contains("master")) ? "master" : "develop"
def JENKINS_ICO = 'https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png'
def OPENSHIFT_ICO = 'https://commons.wikimedia.org/wiki/File:OpenShift-LogoType.svg'

// define groovy functions
import groovy.json.JsonOutput

// send a msg to slack channel that deploy occured
def notifySlack(text, channel, url, attachments) {
    def slackURL = url
    def jenkinsIcon = 'https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png'
    def payload = JsonOutput.toJson([text: text,
        channel: channel,
        username: "Jenkins",
        icon_url: jenkinsIcon,
        attachments: attachments
    ])
    def encodedReq = URLEncoder.encode(payload, "UTF-8")
    sh("curl -s -S -X POST " +
            "--data \'payload=${encodedReq}\' ${slackURL}")    
}

// create a string listing commit msgs occured since last build
@NonCPS
def getChangeString() {
  MAX_MSG_LEN = 512
  def changeString = ""
  def changeLogSets = currentBuild.changeSets
  for (int i = 0; i < changeLogSets.size(); i++) {
     def entries = changeLogSets[i].items
     for (int j = 0; j < entries.length; j++) {
         def entry = entries[j]
         truncated_msg = entry.msg.take(MAX_MSG_LEN)
         changeString += " - ${truncated_msg} [${entry.author}]\n"
     }
  }
  if (!changeString) {
     changeString = "No changes"
  }
  return changeString
}

// pipeline

// Note: openshiftVerifyDeploy requires policy to be added:
// oc policy add-role-to-user view system:serviceaccount:devex-platform-tools:jenkins -n devex-platform-dev
// oc policy add-role-to-user view system:serviceaccount:devex-platform-tools:jenkins -n devex-platform-test
// oc policy add-role-to-user view system:serviceaccount:devex-platform-tools:jenkins -n devex-platform-prod

// define job properties - keep 10 builds only
properties([[$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10']]])

// Part 1 - CI - Source code scanning, build, dev deploy

podTemplate(label: 'jenkins-py3nodejs', name: 'jenkins-py3nodejs', serviceAccount: 'jenkins', cloud: 'openshift', containers: [
containerTemplate(
    name: 'jnlp',
    image: '172.50.0.2:5000/openshift/jenkins-slave-py3nodejs',
    resourceRequestCpu: '500m',
    resourceLimitCpu: '1000m',
    resourceRequestMemory: '1Gi',
    resourceLimitMemory: '2Gi',
    workingDir: '/tmp',
    command: '',
    args: '${computer.jnlpmac} ${computer.name}'
    )
])
{
    node('jenkins-py3nodejs') {


        stage('checkout') {
            echo "checking out source"
            echo "Build: ${BUILD_ID}"
            checkout scm
            SLACK_TOKEN = sh (
                script: """oc get secret/slack -o template --template="{{.data.token}}" | base64 --decode""",
                returnStdout: true).trim()
            GIT_COMMIT_SHORT_HASH = sh (
				script: """git describe --always""", returnStdout: true
				).trim()
			GIT_COMMIT_AUTHOR = sh (
				script: """git show -s --pretty=%an""", returnStdout: true
				).trim()

        }
		stage('build python') {
				echo "Building..."
				openshiftBuild bldCfg: BUILDCFG_BASE, verbose: 'false', showBuildLogs: 'true'
					sleep 5
				// openshiftVerifyBuild bldCfg: BUILDCFG_NAME
					echo ">>> Get Image Hash"
					IMAGE_HASH = sh (
					  script: """oc get istag ${IMAGE_BASE_NAME}:latest -o template --template=\"{{.image.dockerImageReference}}\"|awk -F \":\" \'{print \$3}\'""",
						returnStdout: true).trim()
					echo ">> IMAGE_HASH: ${IMAGE_HASH}"
				echo ">>>> Build Complete"
		}

		stage('assemble runtime') {
				echo "Building..."
				openshiftBuild bldCfg: BUILDCFG_RUNTIME, verbose: 'false', showBuildLogs: 'true'
					sleep 5
				// openshiftVerifyBuild bldCfg: BUILDCFG_NAME
					echo ">>> Get Image Hash"
					IMAGE_HASH = sh (
					  script: """oc get istag ${IMAGE_RUNTIME_NAME}:latest -o template --template=\"{{.image.dockerImageReference}}\"|awk -F \":\" \'{print \$3}\'""",
						returnStdout: true).trim()
					echo ">> IMAGE_HASH: ${IMAGE_HASH}"
				echo ">>>> Build Complete"
		}

		stage('Dev deploy') {
			echo ">>> Tag ${IMAGE_HASH} with ${DEV_TAG_NAME}"
			openshiftTag destStream: IMAGE_RUNTIME_NAME, verbose: 'false', destTag: DEV_TAG_NAME, srcStream: IMAGE_RUNTIME_NAME, srcTag: "${IMAGE_HASH}"
				sleep 10
			openshiftVerifyDeployment depCfg: DEV_DEPLOYMENT_NAME, namespace: DEV_NS, replicaCount: 1, verbose: 'false', verifyReplicaCount: 'false'
			echo ">>>> Deployment Complete"

			// send msg to slack
			def attachment = [:]
            attachment.fallback = "See build log for more details"
            attachment.title = "NAMEX-API Build ${BUILD_ID} OK! :heart: :tada:"
            attachment.color = "#00FF00" // Lime Green
            attachment.text = "Changes applied:\n" + getChangeString() //+ "\nCommit ${GIT_COMMIT_SHORT_HASH} by ${GIT_COMMIT_AUTHOR}"
            def details = [:]
            details.type = "button"
            details.text = "Details"
            details.url = "https://jenkins-servicebc-ne-tools.pathfinder.gov.bc.ca/job/servicebc-ne-tools/job/servicebc-ne-tools-namex-api-pipeline/${BUILD_ID}"
            details.short = false
            attachment.actions = [details]
			notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
		}
	}
}
// Part 2 - Integration Testing API

stage('API Test DEV') {
    //every time a change is made in pod template the name must be changed too
	podTemplate(label: 'nodejs-python3nodejs3', name: 'nodejs-python3nodejs3', serviceAccount: 'jenkins', cloud: 'openshift', containers: [
	containerTemplate(
		name: 'jnlp',
		image: '172.50.0.2:5000/openshift/jenkins-slave-python3nodejs',
		resourceRequestCpu: '500m',
		resourceLimitCpu: '1000m',
		resourceRequestMemory: '1Gi',
		resourceLimitMemory: '2Gi',
		workingDir: '/tmp',
		command: '',
		args: '${computer.jnlpmac} ${computer.name}',
		envVars: [
            envVar(key:'BASEURL', value: "https://namex-dev.pathfinder.gov.bc.ca"),
            secretEnvVar(key: 'DEV_API_TEST_USER', secretName: 'apitest-secrets-dev', secretKey: 'username'),
            secretEnvVar(key: 'DEV_API_TEST_PASSWORD', secretName: 'apitest-secrets-dev', secretKey: 'password'),
            secretEnvVar(key: 'DEV_API_TEST_AUTH_SERVER', secretName: 'apitest-secrets-dev', secretKey: 'authurl'),
            secretEnvVar(key: 'DEV_API_TEST_CLIENT_ID', secretName: 'apitest-secrets-dev', secretKey: 'clientid'),
            secretEnvVar(key: 'DEV_API_TEST_CLIENT_SECRET', secretName: 'apitest-secrets-dev', secretKey: 'client_secret')
        ]
	  )
	])
	{
        node('nodejs-python3nodejs3') {
            //the checkout is mandatory, otherwise functional test would fail
                echo "checking out source"
                echo "Build: ${BUILD_ID}"
                sh '''#!/bin/bash
                    echo BASEURL=$BASEURL
                    echo DEV_API_TEST_USER = $DEV_API_TEST_USER
                    echo DEV_API_TEST_CLIENT_ID = $DEV_API_TEST_CLIENT_ID
                    echo DEV_API_TEST_AUTH_SERVER = $DEV_API_TEST_AUTH_SERVER
                '''
                //input(message: "Verify Environment variables. Continue?")
                checkout scm
                dir('api/tests/postman') {

                    sh 'npm install newman'

                    try {
                        sh './node_modules/newman/bin/newman.js run ./namex-pipeline-dev.postman_collection.json --global-var userid=$DEV_API_TEST_USER --global-var password=$DEV_API_TEST_PASSWORD --global-var url="${BASEURL}" --global-var authurl=$DEV_API_TEST_AUTH_SERVER --global-var clientid=$DEV_API_TEST_CLIENT_ID --global-var client_secret=$DEV_API_TEST_CLIENT_SECRET --global-var realm=nest -r cli,junit,html'
                        def attachment = [:]
                        attachment.fallback = "See build log for more details"
                        attachment.title = "NAMEX-API-DEV newman tests PASSED! :white_check_mark:"
                        attachment.color = "#00FF00" // lime green
                        notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
                    } catch (Exception e) {
                        def attachment = [:]
                        attachment.fallback = "See build log for more details"
                        attachment.title = "NAMEX-API-DEV newman tests FAILED! :nauseated_face:"
                        attachment.color = "danger" // red
				        attachment.text = "- click _Details_ in build message above for more info" //+ "\nCommit ${GIT_COMMIT_SHORT_HASH} by ${GIT_COMMIT_AUTHOR}"
                        notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
                    } finally {
                        junit 'newman/*.xml'
                        publishHTML (target: [
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: 'newman',
                                    reportFiles: 'newman*.html',
                                    reportName: "API Test Report"
                                ])
                        stash includes: 'newman/*.xml', name: 'api-tests'
                    }
                } // end dir
		    } //end node
	    } //end podTemplate
    } //end stage

// Part 3 - Security scan of deployed app in dev

// ensure pod labels/names are unique
def zappodlabel = "myapp-zap-${UUID.randomUUID().toString()}"
podTemplate(label: zappodlabel, name: zappodlabel, serviceAccount: 'jenkins', cloud: 'openshift', containers: [
  containerTemplate(
    name: 'jnlp',
    image: '172.50.0.2:5000/openshift/jenkins-slave-zap',
    resourceRequestCpu: '500m',
    resourceLimitCpu: '1000m',
    resourceRequestMemory: '3Gi',
    resourceLimitMemory: '4Gi',
    workingDir: '/home/jenkins',
    command: '',
    args: '${computer.jnlpmac} ${computer.name}'
  )
]) {
     stage('ZAP Security Scan') {
        node(zappodlabel) {
          sleep 60
          def retVal = sh returnStatus: true, script: '/zap/zap-baseline.py -r baseline.html -t http://namex-api-dev.pathfinder.gov.bc.ca/'
          // publishHTML([allowMissing: false`, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/zap/wrk', reportFiles: 'baseline.html', reportName: 'ZAP Baseline Scan', reportTitles: 'ZAP Baseline Scan'])
          echo "Return value is: ${retVal}"
          SLACK_TOKEN = sh (
                    script: """oc get secret/slack -o template --template="{{.data.token}}" | base64 --decode""",
                    returnStdout: true).trim()
          def attachment = [:]
          attachment.title = "NAMEX-API ready for DEPLOY to TEST"
          attachment.color = "#ffff00" // yellow
          def input = [:]
          input.type = "button"
          input.text = "Proceed/Abort?"
          input.url = "https://jenkins-servicebc-ne-tools.pathfinder.gov.bc.ca/job/servicebc-ne-tools/job/servicebc-ne-tools-namex-api-pipeline/${BUILD_ID}/input"
          input.short = false

          attachment.actions = [input]
          notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
        }
     }
  }

// Part 4 - deploy to test
stage('deploy-test') {
def abort = false;
  timeout(time: 1, unit: 'DAYS') {
      input message: "Deploy to test?", submitter: 'admin,ljtrent-admin,thorwolpert-admin,rarmitag-admin,kialj876-edit,katiemcgoff-edit'
  }
  node('master') {
      SLACK_TOKEN = sh (
                    script: """oc get secret/slack -o template --template="{{.data.token}}" | base64 --decode""",
                    returnStdout: true).trim()
      if (abort) {
        def attachment = [:]
        attachment.fallback = "See build log for more details"
        attachment.title = "NAMEX-API-TEST ABORTED :boom:"
        attachment.color = "danger" // red
        notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
        echo ">>>> Deployment Aborted"
        currentBuild.result = 'ABORTED'
        error('Aborted')
      } else {
        echo ">>> Tag ${TST_TAG_NAME} with ${TST_BCK_TAG_NAME}"
        openshiftTag destStream: IMAGE_RUNTIME_NAME, verbose: 'false', destTag: TST_BCK_TAG_NAME, srcStream: IMAGE_RUNTIME_NAME, srcTag: TST_TAG_NAME
        echo ">>> Tag ${IMAGE_HASH} with ${TST_TAG_NAME}"
        openshiftTag destStream: IMAGE_RUNTIME_NAME, verbose: 'false', destTag: TST_TAG_NAME, srcStream: IMAGE_RUNTIME_NAME, srcTag: "${IMAGE_HASH}"
        sleep 5
        openshiftVerifyDeployment depCfg: TST_DEPLOYMENT_NAME, namespace: TST_NS, replicaCount: 1, verbose: 'false', verifyReplicaCount: 'false'
        echo ">>>> Deployment Complete"
        def attachment = [:]
        attachment.fallback = "See build log for more details"
        attachment.title = "NAMEX-API-TEST DEPLOYED :rocket:"
        attachment.color = "#00FF00" // Lime Green
        notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
      }
  }
}

//Part 5 - Integration Testing API on test
stage('API Test TEST') {
    //every time a change is made in pod template the name must be changed too
	podTemplate(label: 'nodejs-python3nodejs5', name: 'nodejs-python3nodejs5', serviceAccount: 'jenkins', cloud: 'openshift', containers: [
	containerTemplate(
		name: 'jnlp',
		image: '172.50.0.2:5000/openshift/jenkins-slave-python3nodejs',
		resourceRequestCpu: '500m',
		resourceLimitCpu: '1000m',
		resourceRequestMemory: '1Gi',
		resourceLimitMemory: '2Gi',
		workingDir: '/tmp',
		command: '',
		args: '${computer.jnlpmac} ${computer.name}',
		envVars: [
            envVar(key:'BASEURL', value: "https://namex-test.pathfinder.gov.bc.ca"),
            secretEnvVar(key: 'TEST_API_TEST_USER', secretName: 'apitest-secrets-test', secretKey: 'username'),
            secretEnvVar(key: 'TEST_API_TEST_PASSWORD', secretName: 'apitest-secrets-test', secretKey: 'password'),
            secretEnvVar(key: 'TEST_API_TEST_AUTH_SERVER', secretName: 'apitest-secrets-test', secretKey: 'authurl'),
            secretEnvVar(key: 'TEST_API_TEST_CLIENT_ID', secretName: 'apitest-secrets-test', secretKey: 'clientid'),
            secretEnvVar(key: 'TEST_API_TEST_CLIENT_SECRET', secretName: 'apitest-secrets-test', secretKey: 'client_secret')
        ]
	  )
	])
	{
        node('nodejs-python3nodejs5') {
        //the checkout is mandatory, otherwise functional test would fail
            echo "checking out source"
            echo "Build: ${BUILD_ID}"
            sh '''#!/bin/bash
                echo BASEURL=$BASEURL
                echo TEST_API_TEST_USER = $TEST_API_TEST_USER
                echo TEST_API_TEST_AUTH_SERVER = $TEST_API_TEST_AUTH_SERVER
                echo TEST_API_TEST_CLIENT_ID = $TEST_API_TEST_CLIENT_ID
            '''
            //input(message: "Verify Environment variables. Continue?")
            checkout scm
            SLACK_TOKEN = sh (
                script: """oc get secret/slack -o template --template="{{.data.token}}" | base64 --decode""",
                returnStdout: true).trim()
            dir('api/tests/postman') {

                sh 'npm install newman'

                try {
                    sh './node_modules/newman/bin/newman.js run ./namex-pipeline-test.postman_collection.json --global-var userid=$TEST_API_TEST_USER --global-var password=$TEST_API_TEST_PASSWORD --global-var url="${BASEURL}" --global-var authurl=$TEST_API_TEST_AUTH_SERVER --global-var clientid=$TEST_API_TEST_CLIENT_ID --global-var client_secret=$TEST_API_TEST_CLIENT_SECRET --global-var realm=nest -r cli,junit,html'
                    def attachment = [:]
                    attachment.fallback = "See build log for more details"
                    attachment.title = "NAMEX-API-TEST newman tests PASSED! :white_check_mark: :white_check_mark:"
                    attachment.color = "#00FF00" // lime green
                    notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
                } catch (Exception e) {
                    def attachment = [:]
                    attachment.fallback = "See build log for more details"
                    attachment.title = "NAMEX-API-TEST newman tests FAILED! :nauseated_face: :nauseated_face:"
                    attachment.color = "danger" // red
                    attachment.text = "- click _Details_ in build message above for more info" //+ "\nCommit ${GIT_COMMIT_SHORT_HASH} by ${GIT_COMMIT_AUTHOR}"
                    notifySlack("namex-api", "#name-examination", "https://hooks.slack.com/services/${SLACK_TOKEN}", [attachment])
                } finally {
                        junit 'newman/*.xml'
                        publishHTML (target: [
                                    allowMissing: false,
                                    alwaysLinkToLastBuild: false,
                                    keepAll: true,
                                    reportDir: 'newman',
                                    reportFiles: 'newman*.html',
                                    reportName: "API Test Report"
                                ])
                        stash includes: 'newman/*.xml', name: 'api-tests'
                }
            } // end dir
        } //end node
    } //end podTemplate
} //end stage