name: Namex NR Day Job CI

on:
  pull_request:
    paths:
      - "jobs/nr-day-job/**"
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./jobs/nr-day-job

jobs:
  nr-day-job-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "nr-day-job"
      working_directory: "./jobs/nr-day-job"
      codecov_flag: "nr-day-job"
      skip_isort: "true"
      skip_black: "true"