name: Namex OCP Relay API CD

on:
  push:
    branches:
      - main
    paths:
      - "services/ocp-relay/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  ocp-relay-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd-ocp.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "ocp-relay"
      working_directory: "./services/ocp-relay"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_GOLD_DOCKER_REGISTRY }}
      OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_GOLD_LOGIN_REGISTRY }}
      OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_GOLD_SA_NAME }}
      OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_GOLD_SA_TOKEN }}
      OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_GOLD_REPOSITORY }}
