name: Namex SFTP NUANS Report Job CI

on:
  pull_request:
    paths:
      - "jobs/sftp-nuans-report/**"
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./jobs/sftp-nuans-report

jobs:
  namex-sftp-nuans-report-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "nuans-report"
      working_directory: "./jobs/sftp-nuans-report"
      codecov_flag: "namexnuansreport"
      skip_isort: "true"
      skip_black: "true"