name: Namex Solr Admin App CD

on:
  push:
    branches:
      - main
    paths:
      - "solr-admin-app/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod

jobs:
  namex-solr-admin-app-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "namex-solr-admin-app"
      working_directory: "./solr-admin-app"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}