name: Solr Synonymns API CI

on:
  pull_request:
    paths:
      - "solr-synonyms-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./solr-synonyms-api

jobs:
  solr-synonyms-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "solr-synonyms-api"
      working_directory: "./solr-synonyms-api"
      codecov_flag: "solrsynonymsapi"
      skip_isort: "true"
      skip_black: "true"