name: Namex Solr Synonyms API CI

on:
  pull_request:
    paths:
      - "solr-synonyms-api/**"
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./solr-synonyms-api

jobs:
  namex-solr-synonyms-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "namex-solr-syn-api"
      working_directory: "./solr-synonyms-api"
      codecov_flag: "namexsolrsynonymsapi"
      skip_isort: "true"
      skip_black: "true"